# Generated by Django 3.1.dev20200104194911 on 2020-01-05 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CCFInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=64)),
                ('full_name', models.CharField(max_length=500)),
                ('published', models.CharField(max_length=100)),
                ('url_link', models.CharField(max_length=200)),
                ('classes', models.CharField(max_length=2)),
                ('subject', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'CCFInfo',
                'verbose_name_plural': 'CCFInfos',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
