# Generated by Django 3.0.4 on 2020-04-09 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CCFInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=64)),
                ('full_name', models.CharField(max_length=500)),
                ('full_name_u', models.CharField(default=' ', max_length=500)),
                ('published', models.CharField(max_length=100)),
                ('url_link', models.CharField(max_length=200)),
                ('classes', models.CharField(max_length=2)),
                ('subject', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=20)),
                ('where', models.CharField(max_length=200)),
                ('when', models.CharField(max_length=200)),
                ('paper_deadline', models.CharField(max_length=50)),
                ('notification', models.CharField(default=' ', max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'CCFInfo',
                'verbose_name_plural': 'CCFInfos',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ConferenceInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('con_name', models.CharField(max_length=100)),
                ('con_sname', models.CharField(max_length=20)),
                ('con_classes', models.CharField(max_length=50)),
                ('con_where', models.CharField(max_length=200)),
                ('con_when', models.CharField(max_length=200)),
                ('con_paper_deadline', models.CharField(max_length=100)),
                ('con_notification', models.CharField(max_length=100)),
                ('con_index', models.CharField(max_length=20)),
                ('con_cfp', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('con_serach_num', models.IntegerField()),
                ('con_hot', models.BooleanField()),
            ],
            options={
                'verbose_name': 'ConferenceInfo',
                'verbose_name_plural': 'ConferenceInfos',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='IndexInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issn', models.CharField(max_length=10)),
                ('year', models.CharField(max_length=10)),
                ('index_num', models.CharField(max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('exer', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'IndexInfo',
                'verbose_name_plural': 'IndexInfos',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='JournalsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journal_name', models.CharField(max_length=500)),
                ('journal_name_u', models.CharField(max_length=500)),
                ('journal_short_name', models.CharField(max_length=100)),
                ('journal_issn', models.CharField(max_length=24)),
                ('journal_office', models.CharField(max_length=400)),
                ('journal_public', models.CharField(max_length=400)),
                ('journal_desc', models.CharField(max_length=400)),
                ('journal_jcr', models.CharField(max_length=24)),
                ('journal_q', models.CharField(max_length=24)),
                ('journal_b_sub', models.CharField(max_length=100)),
                ('journal_s_sub', models.CharField(max_length=500)),
                ('journal_sci', models.CharField(max_length=30)),
                ('journal_ccf', models.CharField(max_length=30)),
                ('journal_accept', models.CharField(max_length=50)),
                ('journal_oa', models.CharField(max_length=10)),
                ('journal_index', models.CharField(max_length=50)),
                ('journal_h_index', models.CharField(max_length=50)),
                ('journal_total_index', models.CharField(max_length=50)),
                ('journal_index_self', models.CharField(max_length=40)),
                ('journal_period', models.CharField(max_length=50)),
                ('journal_papers', models.CharField(max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('journal_search_num', models.IntegerField()),
                ('journal_hot', models.BooleanField()),
            ],
            options={
                'verbose_name': 'JournalsInfo',
                'verbose_name_plural': 'JournalsInfos',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
