# Generated by Django 3.0.4 on 2020-03-12 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dr_server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journal_name', models.CharField(max_length=500)),
                ('journal_short_name', models.CharField(max_length=100)),
                ('journal_issn', models.CharField(max_length=24)),
                ('journal_office', models.CharField(max_length=400)),
                ('journal_contribute', models.CharField(max_length=400)),
                ('journal_focus', models.CharField(max_length=400)),
                ('journal_h_index', models.FloatField()),
                ('journal_jcr', models.CharField(max_length=24)),
                ('journal_group', models.CharField(max_length=100)),
                ('journal_subgroups', models.CharField(max_length=500)),
                ('journal_sci', models.CharField(max_length=30)),
                ('journal_ccf', models.CharField(max_length=30)),
                ('journal_accept_ratio', models.FloatField()),
                ('journal_amount', models.IntegerField()),
                ('journal_cited', models.IntegerField()),
                ('journal_cited_self', models.FloatField()),
                ('journal_cs', models.FloatField()),
                ('journal_cs_sjr', models.FloatField()),
                ('journal_cs_snip', models.FloatField()),
                ('journal_publish_cycle', models.CharField(max_length=24)),
            ],
            options={
                'verbose_name': 'JournalsInfo',
                'verbose_name_plural': 'JournalsInfos',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
