# Generated by Django 3.0.4 on 2020-04-01 04:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dr_server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConferenceInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('con_name', models.CharField(max_length=100)),
                ('con_sname', models.CharField(max_length=20)),
                ('con_classes', models.CharField(max_length=50)),
                ('con_where', models.CharField(max_length=200)),
                ('con_when', models.CharField(max_length=200)),
                ('con_paper_deadline', models.CharField(max_length=100)),
                ('con_notification', models.CharField(max_length=100)),
                ('con_index', models.CharField(max_length=20)),
                ('con_cfp', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('con_serach_num', models.IntegerField()),
                ('con_hot', models.BooleanField()),
            ],
            options={
                'verbose_name': 'ConferenceInfo',
                'verbose_name_plural': 'ConferenceInfos',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='JournalsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journal_name', models.CharField(max_length=500)),
                ('journal_name_u', models.CharField(max_length=500)),
                ('journal_short_name', models.CharField(max_length=100)),
                ('journal_issn', models.CharField(max_length=24)),
                ('journal_office', models.CharField(max_length=400)),
                ('journal_public', models.CharField(max_length=400)),
                ('journal_desc', models.CharField(max_length=400)),
                ('journal_jcr', models.CharField(max_length=24)),
                ('journal_q', models.CharField(max_length=24)),
                ('journal_b_sub', models.CharField(max_length=100)),
                ('journal_s_sub', models.CharField(max_length=500)),
                ('journal_sci', models.CharField(max_length=30)),
                ('journal_ccf', models.CharField(max_length=30)),
                ('journal_accept', models.CharField(max_length=50)),
                ('journal_oa', models.BooleanField()),
                ('journal_index', models.FloatField()),
                ('journal_h_index', models.FloatField()),
                ('journal_total_index', models.IntegerField()),
                ('journal_index_self', models.FloatField()),
                ('journal_period', models.CharField(max_length=50)),
                ('journal_papers', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('journal_search_num', models.IntegerField()),
                ('journal_hot', models.BooleanField()),
            ],
            options={
                'verbose_name': 'JournalsInfo',
                'verbose_name_plural': 'JournalsInfos',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='ccfinfo',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ccfinfo',
            name='full_name_u',
            field=models.CharField(default=' ', max_length=500),
        ),
        migrations.AddField(
            model_name='ccfinfo',
            name='notification',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AddField(
            model_name='ccfinfo',
            name='paper_deadline',
            field=models.CharField(default=' ', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ccfinfo',
            name='when',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ccfinfo',
            name='where',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
    ]
